module.exports = {

  eurostat: "https://ec.europa.eu/eurostat/cache/GISCO/distribution/v2",

  import: {
    projection: [4326],
    year: [2010,2013,2016,2021],
    precision: ['60','20','10','03','01'],
    level: [false,0,1,2,3]
  },

  eu28: [
    "DE", "EL", "FR", "PL", "UK", "SI", "BE", "BG", "CZ", "DK", "EE", "IE",
    "ES", "HR", "IT", "CY", "LV", "LT", "LU", "HU", "MT", "NL", "AT", "PT",
    "RO", "SK", "FI", "SE"
  ],

  eu27: [
    "DE", "EL", "FR", "PL", "SI", "BE", "BG", "CZ", "DK", "EE", "IE", "ES",
    "HR", "IT", "CY", "LV", "LT", "LU", "HU", "MT", "NL", "AT", "PT", "RO",
    "SK", "FI", "SE"
  ],

  all: [
    "AD", "AE", "AF", "AG", "AI", "AL", "AM", "AO", "AQ", "AR", "AS", "AT",
    "AU", "AW", "AZ", "BA", "BB", "BD", "BE", "BF", "BG", "BH", "BI", "BJ",
    "BL", "BM",  "BN", "BO", "BQ", "BR", "BS", "BT", "BV", "BW", "BY", "BZ",
    "CA", "CC", "CD", "CF", "CG", "CH", "CI", "CK", "CL", "CM", "CN", "CO",
    "CP", "CR", "CU", "CV", "CW", "CX", "CY", "CZ", "DE", "DJ", "DK", "DM",
    "DO", "DZ", "EC", "EE", "EG", "EH", "EL", "ER", "ES", "ET", "FI", "FJ",
    "FK", "FM", "FO", "FR", "GA", "GD", "GE", "GG", "GH", "GL", "GM", "GN",
    "GQ", "GS", "GT", "GU", "GW", "GY", "HK", "HM", "HN", "HR", "HT", "HU",
    "ID", "IE", "IL", "IM", "IN", "IO", "IQ", "IR", "IS", "IT", "JM", "JO",
    "JP", "KE", "KG", "KH", "KI", "KM", "KN", "KP", "KR", "KW", "KY", "KZ",
    "LA", "LB", "LC", "LI", "LK", "LR", "LS", "LT", "LU", "LV", "LY", "MA",
    "MC", "MD", "ME", "MG", "MH", "MK", "ML", "MM", "MN", "MO", "MP", "MR",
    "MS", "MT", "MU", "MV", "MW", "MX", "MY", "MZ", "NA", "NC", "NE", "NF",
    "NG", "NI", "NL", "NO", "NP", "NR", "NU", "NZ", "OM", "PA", "PE", "PF",
    "PG", "PH", "PK", "PL", "PM", "PN", "PR", "PS", "PT", "PW", "PY", "QA",
    "RO", "RS", "RU", "RW", "SA", "SB", "SC", "SD", "SE", "SG", "SH", "SI",
    "SJ", "SK", "SL", "SM", "SN", "SO", "SR", "SS", "ST", "SV", "SX", "SY",
    "SZ", "TC", "TD", "TF", "TG", "TH", "TJ", "TK", "TL", "TM", "TN", "TO",
    "TR", "TT", "TV", "TZ", "UA", "UG", "UK", "UM", "US", "UY", "UZ", "VA",
    "VC", "VE", "VG", "VI", "VN", "VU", "WF", "WS", "YE", "ZA", "ZM", "ZW"
  ],

  countries_translate: {
    "bg": {
      "AD": "Андора",
      "AL": "Албания",
      "AM": "Армения",
      "AT": "Австрия",
      "AZ": "Азербайджан",
      "BA": "Босна и Херцеговина",
      "BE": "Белгия",
      "BG": "България",
      "BY": "Беларус",
      "CH": "Швейцария",
      "CY": "Кипър",
      "CZ": "Чехия",
      "DE": "Германия",
      "DK": "Дания",
      "EE": "Естония",
      "EL": "Гърция",
      "ES": "Испания",
      "FI": "Финландия",
      "FR": "Франция",
      "GE": "Грузия",
      "HR": "Хърватия",
      "HU": "Унгария",
      "IE": "Ирландия",
      "IS": "Исландия",
      "IT": "Италия",
      "KS": "Косово",
      "LI": "Лихтенщайн",
      "LT": "Литва",
      "LU": "Люксембург",
      "LV": "Латвия",
      "MC": "Монако",
      "MD": "Молдова",
      "ME": "Черна гора",
      "MK": "бивша югославска република Македония",
      "MT": "Малта",
      "NL": "Нидерландия",
      "NO": "Норвегия",
      "PL": "Полша",
      "PT": "Португалия",
      "RO": "Румъния",
      "RS": "Сърбия",
      "RU": "Русия",
      "SE": "Швеция",
      "SI": "Словения",
      "SK": "Словакия",
      "SM": "Сан Марино",
      "TR": "Турция",
      "UA": "Украйна",
      "UK": "Обединено кралство",
      "VA": "Ватикан"
    },
    "cs": {
      "AD": "Andorra",
      "AL": "Albánie",
      "AM": "Arménie",
      "AT": "Rakousko",
      "AZ": "Ázerbájdžán",
      "BA": "Bosna a Hercegovina",
      "BE": "Belgie",
      "BG": "Bulharsko",
      "BY": "Bělorusko",
      "CH": "Švýcarsko",
      "CY": "Kypr",
      "CZ": "Česko",
      "DE": "Německo",
      "DK": "Dánsko",
      "EE": "Estonsko",
      "EL": "Řecko",
      "ES": "Španělsko",
      "FI": "Finsko",
      "FR": "Francie",
      "GE": "Gruzie",
      "HR": "Chorvatsko",
      "HU": "Maďarsko",
      "IE": "Irsko",
      "IS": "Island",
      "KS": "Kosovo*",
      "IT": "Itálie",
      "LI": "Lichtenštejnsko",
      "LT": "Litva",
      "LU": "Lucembursko",
      "LV": "Lotyšsko",
      "MC": "Monaco",
      "MD": "Moldavsko",
      "ME": "Černá Hora",
      "MK": "Bývalá jugoslávská republika Makedonie",
      "MT": "Malta",
      "NL": "Nizozemsko",
      "NO": "Norsko",
      "PL": "Polsko",
      "PT": "Portugalsko",
      "RO": "Rumunsko",
      "RS": "Srbsko",
      "RU": "Rusko",
      "SE": "Švédsko",
      "SI": "Slovinsko",
      "SK": "Slovensko",
      "SM": "San Marino",
      "TR": "Turecko",
      "UA": "Ukrajina",
      "UK": "Spojené království",
      "VA": "Vatikán"
    },
    "da": {
      "AD": "Andorra ",
      "AL": "Albanien",
      "AM": "Armenien",
      "AT": "Østrig",
      "AZ": "Aserbajdsjan",
      "BA": "Bosnien-Hercegovina",
      "BE": "Belgien",
      "BG": "Bulgarien",
      "BY": "Hviderusland",
      "CH": "Schweiz",
      "CY": "Cypern",
      "CZ": "Tjekkiet",
      "DE": "Tyskland",
      "DK": "Danmark",
      "EE": "Estland",
      "EL": "Grækenland",
      "ES": "Spanien",
      "FI": "Finland",
      "FR": "Frankrig",
      "GE": "Georgien",
      "HR": "Kroatien",
      "HU": "Ungarn",
      "IE": "Irland",
      "IS": "Island",
      "IT": "Italien",
      "KS": "Kosovo*",
      "LI": "Liechtenstein",
      "LT": "Litauen",
      "LU": "Luxembourg",
      "LV": "Letland",
      "MC": "Monaco",
      "MD": "Moldova",
      "ME": "Montenegro",
      "MK": "Den Tidligere Jugoslaviske Republik Makedonien",
      "MT": "Malta",
      "NL": "Holland",
      "NO": "Norge",
      "PL": "Polen",
      "PT": "Portugal",
      "RO": "Rumænien",
      "RS": "Serbien",
      "RU": "Rusland",
      "SE": "Sverige",
      "SI": "Slovenien",
      "SK": "Slovakiet",
      "SM": "San Marino",
      "TR": "Tyrkiet",
      "UA": "Ukraine",
      "UK": "Det Forenede Kongerige",
      "VA": "Vatikanstaten"
    },
    "de": {
      "AD": "Andorra",
      "AL": "Albanien",
      "AM": "Armenien",
      "AT": "Österreich",
      "AZ": "Aserbaidschan",
      "BA": "Bosnien und Herzegowina",
      "BE": "Belgien",
      "BG": "Bulgarien",
      "BY": "Belarus",
      "CH": "Schweiz",
      "CY": "Zypern",
      "CZ": "Tschechien",
      "DE": "Deutschland",
      "DK": "Dänemark",
      "EE": "Estland",
      "EL": "Griechenland",
      "ES": "Spanien",
      "FI": "Finnland",
      "FR": "Frankreich",
      "GE": "Georgien",
      "HR": "Kroatien",
      "HU": "Ungarn",
      "IE": "Irland",
      "IS": "Island",
      "IT": "Italien",
      "KS": "Kosovo*",
      "LI": "Liechtenstein",
      "LT": "Litauen",
      "LU": "Luxemburg",
      "LV": "Lettland",
      "MC": "Monaco",
      "MD": "Moldau",
      "ME": "Montenegro",
      "MK": "Die ehemalige jugoslawische Republik Mazedonien",
      "MT": "Malta",
      "NL": "Die Niederlande",
      "NO": "Norwegen",
      "PL": "Polen",
      "PT": "Portugal",
      "RO": "Rumänien",
      "RS": "Serbien",
      "RU": "Russland",
      "SE": "Schweden",
      "SI": "Slowenien",
      "SK": "Slowakei",
      "SM": "San Marino",
      "TR": "Türkei",
      "UA": "Ukraine",
      "UK": "Vereinigtes Königreich",
      "VA": "Vatikan"
    },
    "et": {
      "AD": "Andorra",
      "AL": "Albaania",
      "AM": "Armeenia",
      "AT": "Austria",
      "AZ": "Aserbaidžaan",
      "BA": "Bosnia-Hertsegovina",
      "BE": "Belgia",
      "BG": "Bulgaaria",
      "BY": "Valgevene",
      "CH": "Šveits",
      "CY": "Küpros",
      "CZ": "Tšehhi",
      "DE": "Saksamaa",
      "DK": "Taani",
      "EE": "Eesti",
      "EL": "Kreeka",
      "ES": "Hispaania",
      "FI": "Soome",
      "FR": "Prantsusmaa",
      "GE": "Gruusia",
      "HR": "Horvaatia",
      "HU": "Ungari",
      "IE": "Iirimaa",
      "IS": "Island",
      "IT": "Itaalia",
      "KS": "Kosovo*",
      "LI": "Liechtenstein",
      "LT": "Leedu",
      "LU": "Luksemburg",
      "LV": "Läti",
      "MC": "Monaco",
      "MD": "Moldova",
      "ME": "Montenegro",
      "MK": "endine Jugoslaavia Makedooniavabariik",
      "MT": "Malta",
      "NL": "Madalmaad",
      "NO": "Norra",
      "PL": "Poola",
      "PT": "Portugal",
      "RO": "Rumeenia",
      "RS": "Serbia",
      "RU": "Venemaa",
      "SE": "Rootsi",
      "SI": "Sloveenia",
      "SK": "Slovakkia",
      "SM": "San Marino",
      "TR": "Türgi",
      "UA": "Ukraina",
      "UK": "Ühendkuningriik",
      "VA": "Vatikan"
    },
    "el": {
      "AD": "Ανδόρα",
      "AL": "Αλβανία",
      "AM": "Αρμενία",
      "AT": "Αυστρία",
      "AZ": "Αζερμπαϊτζάν",
      "BA": "Βοσνία-Ερζεγοβίνη",
      "BE": "Βέλγιο",
      "BG": "Βουλγαρία",
      "BY": "Λευκορωσία",
      "CH": "Ελβετία",
      "CY": "Κύπρος",
      "CZ": "Τσεχία",
      "DE": "Γερμανία",
      "DK": "Δανία",
      "EE": "Εσθονία",
      "EL": "Ελλάδα",
      "ES": "Ισπανία",
      "FI": "Φινλανδία",
      "FR": "Γαλλία",
      "GE": "Γεωργία",
      "HR": "Κροατία",
      "HU": "Ουγγαρία",
      "IE": "Ιρλανδία",
      "IS": "Ισλανδία",
      "IT": "Ιταλία",
      "KS": "Κοσσυφοπέδιο βάσει",
      "LI": "Λιχτενστάιν",
      "LT": "Λιθουανία",
      "LU": "Λουξεμβούργο",
      "LV": "Λετονία",
      "MC": "Μονακό",
      "MD": "Μολδαβία",
      "ME": "Μαυροβούνιο",
      "MK": "πρώην Γιουγκοσλαβική Δημοκρατία της Μακεδονίας",
      "MT": "Μάλτα",
      "NL": "Κάτω Χώρες",
      "NO": "Νορβηγία",
      "PL": "Πολωνία",
      "PT": "Πορτογαλία",
      "RO": "Ρουμανία",
      "RS": "Σερβία",
      "RU": "Ρωσία",
      "SE": "Σουηδία",
      "SI": "Σλοβενία",
      "SK": "Σλοβακία",
      "SM": "Άγιος Μαρίνος",
      "TR": "Τουρκία",
      "UA": "Ουκρανία",
      "UK": "Ηνωμένο Βασίλειο",
      "VA": "Βατικανό"
    },
    "en": {
      "AD": "Andorra",
      "AL": "Albania",
      "AM": "Armenia",
      "AT": "Austria",
      "AZ": "Azerbaijan",
      "BA": "Bosnia and Herzegovina",
      "BE": "Belgium",
      "BG": "Bulgaria",
      "BY": "Belarus",
      "CH": "Switzerland",
      "CY": "Cyprus",
      "CZ": "Czechia",
      "DE": "Germany",
      "DK": "Denmark",
      "EE": "Estonia",
      "EL": "Greece",
      "ES": "Spain",
      "FI": "Finland",
      "FR": "France",
      "GE": "Georgia",
      "HR": "Croatia",
      "HU": "Hungary",
      "IE": "Ireland",
      "IS": "Iceland",
      "IT": "Italy",
      "KS": "Kosovo*",
      "LI": "Liechtenstein",
      "LT": "Lithuania",
      "LU": "Luxembourg",
      "LV": "Latvia",
      "MC": "Monaco",
      "MD": "Moldova",
      "ME": "Montenegro",
      "MK": "Republic of North Macedonia",
      "MT": "Malta",
      "NL": "Netherlands",
      "NO": "Norway",
      "PL": "Poland",
      "PT": "Portugal",
      "RO": "Romania",
      "RS": "Serbia",
      "RU": "Russia",
      "SE": "Sweden",
      "SI": "Slovenia",
      "SK": "Slovakia",
      "SM": "San Marino",
      "TR": "Turkey",
      "UA": "Ukraine",
      "UK": "United Kingdom",
      "VA": "Vatican City"
    },
    "es": {
      "AD": "Andorra",
      "AL": "Albania",
      "AM": "Armenia",
      "AT": "Austria",
      "AZ": "Azerbaiyán",
      "BA": "Bosnia y Herzegovina",
      "BE": "Bélgica",
      "BG": "Bulgaria",
      "BY": "Belarús",
      "CH": "Suiza",
      "CY": "Chipre",
      "CZ": "Chéquia",
      "DE": "Alemania",
      "DK": "Dinamarca",
      "EE": "Estonia",
      "EL": "Grecia",
      "ES": "España",
      "FI": "Finlandia",
      "FR": "Francia",
      "GE": "Georgia",
      "HR": "Croacia",
      "HU": "Hungría",
      "IE": "Irlanda",
      "IS": "Islandia",
      "IT": "Italia",
      "KS": "Kosovo*",
      "LI": "Liechtenstein",
      "LT": "Lituania",
      "LU": "Luxemburgo",
      "LV": "Letonia",
      "MC": "Mónaco",
      "MD": "Moldavia",
      "ME": "Montenegro",
      "MK": "Antigua República Yugoslava de Macedonia",
      "MT": "Malta",
      "NL": "Países Bajos",
      "NO": "Noruega",
      "PL": "Polonia",
      "PT": "Portugal",
      "RO": "Rumanía",
      "RS": "Serbia",
      "RU": "Rusia",
      "SE": "Suecia",
      "SI": "Eslovenia",
      "SK": "Eslovaquia",
      "SM": "San Marino",
      "TR": "Turquía",
      "UA": "Ucrania",
      "UK": "Reino Unido",
      "VA": "Vaticano"
    },
    "fr": {
      "AD": "Andorre",
      "AL": "Albanie",
      "AM": "Arménie",
      "AT": "Autriche",
      "AZ": "Azerbaïdjan",
      "BA": "Bosnie-et-Herzégovine",
      "BE": "Belgique",
      "BG": "Bulgarie",
      "BY": "Biélorussie",
      "CH": "Suisse",
      "CY": "Chypre",
      "CZ": "Tchéquie",
      "DE": "Allemagne",
      "DK": "Danemark",
      "EE": "Estonie",
      "EL": "Grèce",
      "ES": "Espagne",
      "FI": "Finlande",
      "FR": "France",
      "GE": "Géorgie",
      "HR": "Croatie",
      "HU": "Hongrie",
      "IE": "Irlande",
      "IS": "Islande",
      "IT": "Italie",
      "KS": "Kosovo*",
      "LI": "Liechtenstein",
      "LT": "Lituanie",
      "LU": "Luxembourg",
      "LV": "Lettonie",
      "MC": "Monaco",
      "MD": "Moldavie",
      "ME": "Monténégro",
      "MK": "L’ancienne République yougoslave de Macédoine",
      "MT": "Malte",
      "NL": "Pays-Bas",
      "NO": "Norvège",
      "PL": "Pologne",
      "PT": "Portugal",
      "RO": "Roumanie",
      "RS": "Serbie",
      "RU": "Russie",
      "SE": "Suède",
      "SI": "Slovénie",
      "SK": "Slovaquie",
      "SM": "Saint-Marin",
      "TR": "Turquie",
      "UA": "Ukraine",
      "UK": "Royaume-Uni",
      "VA": "Vatican"
    },
    "ga": {
      "AD": "Andóra",
      "AL": "an Albáin",
      "AM": "an Airméin ",
      "AT": "An Ostair",
      "AZ": "an Asarbaiseáin",
      "BA": "an Bhoisnia agus an Heirseagaivéin",
      "BE": "An Bheilg",
      "BG": "An Bhulgáir",
      "BY": "an Bhealarúis",
      "CH": "An Eilvéis",
      "CY": "An Chipir",
      "CZ": "an tSeicia",
      "DE": "An Ghearmáin",
      "DK": "An Danmhairg",
      "EE": "An Eastóin",
      "EL": "An Ghréig",
      "ES": "An Spáinn",
      "FI": "An Fhionlainn",
      "FR": "An Fhrainc",
      "GE": "An tSeoirsia",
      "HR": "An Chróit",
      "HU": "An Ungáir",
      "IE": "Éire",
      "IS": "An Íoslainn",
      "IT": "An Iodáil",
      "KS": "Kosovo*",
      "LI": "Lichtinstéin",
      "LT": "An Liotuáin",
      "LU": "Lucsamburg",
      "LV": "An Laitvia",
      "MC": "Monacó",
      "MD": "Mholdóiv",
      "ME": "Montainéagró",
      "MK": "Poblacht Iar-Iúgslavach na Macadóine",
      "MT": "Málta",
      "NL": "An Ísiltír",
      "NO": "An Iorua",
      "PL": "An Pholainn",
      "PT": "An Phortaingéil",
      "RO": "An Rómáin",
      "RS": "an tSeirbia",
      "RU": "An Rúis",
      "SE": "An tSualainn",
      "SI": "An tSlóivéin",
      "SK": "An tSlóvaic",
      "SM": "San Mairíne",
      "TR": "an Tuirc",
      "UA": "An Úcráin",
      "UK": "An Ríocht Aontaithe",
      "VA": "An Vatacáin"
    },
    "hr": {
      "AD": "Andora",
      "AL": "Albanija",
      "AM": "Armenija",
      "AT": "Austrija",
      "AZ": "Azerbejdžan",
      "BA": "Bosna i Hercegovina",
      "BE": "Belgija",
      "BG": "Bugarska",
      "BY": "Bjelarus",
      "CH": "Švicarska",
      "CY": "Cipar",
      "CZ": "Češka",
      "DE": "Njemačka",
      "DK": "Danska",
      "EE": "Estonija",
      "EL": "Görögország",
      "ES": "Španjolska",
      "FI": "Finska",
      "FR": "Francuska",
      "GE": "Gruzija",
      "HR": "Hrvatska",
      "HU": "Mađarska",
      "IE": "Irska",
      "IS": "Island",
      "IT": "Italija",
      "KS": "Kosovo*",
      "LI": "Lihtenštajn",
      "LT": "Litva",
      "LU": "Luksemburg",
      "LV": "Latvija",
      "MC": "Monako",
      "MD": "Moldavija",
      "ME": "Crna Gora",
      "MK": "bivša jugoslavenska Republika Makedonija",
      "MT": "Malta",
      "NL": "Nizozemska",
      "NO": "Norveška",
      "PL": "Poljska",
      "PT": "Portugal",
      "RO": "Rumunjska",
      "RS": "Srbija",
      "RU": "Rusija",
      "SE": "Švedska",
      "SI": "Slovenija",
      "SK": "Slovačka",
      "SM": "San Marino",
      "TR": "Turska",
      "UA": "Ukrajina",
      "UK": "Ujedinjena Kraljevina",
      "VA": "Vatikan"
    },
    "it": {
      "AD": "Andorra",
      "AL": "Albania",
      "AM": "Armenia",
      "AT": "Austria",
      "AZ": "Azerbaigian",
      "BA": "Bosnia-Erzegovina",
      "BE": "Belgio",
      "BG": "Bulgaria",
      "BY": "Bielorussia",
      "CH": "Svizzera",
      "CY": "Cipro",
      "CZ": "Cechia",
      "DE": "Germania",
      "DK": "Danimarca",
      "EE": "Estonia",
      "EL": "Grecia",
      "ES": "Spagna",
      "FI": "Finlandia",
      "FR": "Francia",
      "GE": "Georgia",
      "HR": "Croazia",
      "HU": "Ungheria",
      "IE": "Irlanda",
      "IS": "Islanda",
      "IT": "Italia",
      "KS": "Kosovo*",
      "LI": "Liechtenstein",
      "LT": "Lituania",
      "LU": "Lussemburgo",
      "LV": "Lettonia",
      "MC": "Monaco",
      "MD": "Moldova",
      "ME": "Montenegro",
      "MK": "Ex Repubblica iugoslava di Macedonia",
      "MT": "Malta",
      "NL": "Paesi Bassi",
      "NO": "Norvegia",
      "PL": "Polonia",
      "PT": "Portogallo",
      "RO": "Romania",
      "RS": "Serbia",
      "RU": "Russia",
      "SE": "Svezia",
      "SI": "Slovenia",
      "SK": "Slovacchia",
      "SM": "San Marino",
      "TR": "Turchia",
      "UA": "Ucraina",
      "UK": "Regno Unito",
      "VA": "Vaticano"
    },
    "lt": {
      "AD": "Andora",
      "AL": "Albanija",
      "AM": "Armėnija",
      "AT": "Austrija",
      "AZ": "Azerbaidžanas",
      "BA": "Bosnija ir Hercegovina",
      "BE": "Belgija",
      "BG": "Bulgarija",
      "BY": "Baltarusija",
      "CH": "Šveicarija",
      "CY": "Kipras",
      "CZ": "Čekija",
      "DE": "Vokietija",
      "DK": "Danija",
      "EE": "Estija",
      "EL": "Graikija",
      "ES": "Ispanija",
      "FI": "Suomija",
      "FR": "Prancūzija",
      "GE": "Gruzija",
      "HR": "Kroatija",
      "HU": "Vengrija",
      "IE": "Airija",
      "IS": "Islandija",
      "IT": "Italija",
      "KS": "Kosovas",
      "LI": "Lichtenšteinas",
      "LT": "Lietuva",
      "LU": "Liuksemburgas",
      "LV": "Latvija",
      "MC": "Monakas",
      "MD": "Moldavija",
      "ME": "Juodkalnija",
      "MK": "Buvusioji Jugoslavijos Respublika Makedonija",
      "MT": "Malta",
      "NL": "Nyderlandai",
      "NO": "Norvegija",
      "PL": "Lenkija",
      "PT": "Portugalija",
      "RO": "Rumunija",
      "RS": "Serbija",
      "RU": "Rusija",
      "SE": "Švedija",
      "SI": "Slovėnija",
      "SK": "Slovakija",
      "SM": "San Marinas",
      "TR": "Turkija",
      "UA": "Ukraina",
      "UK": "Jungtinė Karalystė",
      "VA": "Vatikanas"
    },
    "lv": {
      "AD": "Andora",
      "AL": "Albānija",
      "AM": "Armēnija",
      "AT": "Austrija",
      "AZ": "Azerbaidžāna",
      "BA": "Bosnija un Hercegovina",
      "BE": "Beļģija",
      "BG": "Bulgārija",
      "BY": "Baltkrievija",
      "CH": "Šveice",
      "CY": "Kipra",
      "CZ": "Čehija",
      "DE": "Vācija",
      "DK": "Dānija",
      "EE": "Igaunija",
      "EL": "Grieķija",
      "ES": "Spānija",
      "FI": "Somija",
      "FR": "Francija",
      "GE": "Gruzija",
      "HR": "Horvātija",
      "HU": "Ungārija",
      "IE": "Īrija",
      "IS": "Islande",
      "IT": "Itālija",
      "KS": "Kosova",
      "LI": "Lihtenšteina",
      "LT": "Lietuva",
      "LU": "Luksemburga",
      "LV": "Latvija",
      "MC": "Monako",
      "MD": "Moldova",
      "ME": "Melnkalne",
      "MK": "Bijusī Dienvidslāvijas Maķedonijas Republika",
      "MT": "Malta",
      "NL": "Nīderlande",
      "NO": "Norvēģija",
      "PL": "Polija",
      "PT": "Portugāle",
      "RO": "Rumānija",
      "RS": "Serbija",
      "RU": "Krievija",
      "SE": "Zviedrija",
      "SI": "Slovēnija",
      "SK": "Slovākija",
      "SM": "Sanmarīno",
      "TR": "Turcija",
      "UA": "Ukraina",
      "UK": "Apvienotā Karaliste",
      "VA": "Vatikāns"
    },
    "hu": {
      "AD": "Andorra",
      "AL": "Albánia",
      "AM": "Örményország",
      "AT": "Ausztria",
      "AZ": "Azerbajdzsán",
      "BA": "Bosznia-Hercegovina",
      "BE": "Belgium",
      "BG": "Bulgária",
      "BY": "Fehéroroszország",
      "CH": "Svájc",
      "CY": "Ciprus",
      "CZ": "Csehország",
      "DE": "Németország",
      "DK": "Dánia",
      "EE": "Észtország",
      "EL": "Görögország",
      "ES": "Spanyolország",
      "FI": "Finnország",
      "FR": "Franciaország",
      "GE": "Grúzia",
      "HR": "Horvátország",
      "HU": "Magyarország",
      "IE": "Írország",
      "IS": "Izland",
      "IT": "Olaszország",
      "KS": "Koszovó",
      "LI": "Liechtenstein",
      "LT": "Litvánia",
      "LU": "Luxemburg",
      "LV": "Lettország",
      "MC": "Monaco",
      "MD": "Moldova",
      "ME": "Montenegró",
      "MK": "Macedónia Volt Jugoszláv Köztársaság",
      "MT": "Málta",
      "NL": "Hollandia",
      "NO": "Norvégia",
      "PL": "Lengyelország",
      "PT": "Portugália",
      "RO": "Románia",
      "RS": "Szerbia",
      "RU": "Oroszország",
      "SE": "Svédország",
      "SI": "Szlovénia",
      "SK": "Szlovákia",
      "SM": "San Marino",
      "TR": "Törökország",
      "UA": "Ukrajna",
      "UK": "Egyesült Királyság",
      "VA": "Vatikán"
    },
    "mt": {
      "AD": "Andorra",
      "AL": "L-Albanija",
      "AM": "Armenja",
      "AT": "L-Awstrija",
      "AZ": "Ażerbajġan",
      "BA": "Il-Bożnija u l-Ħerzegovina",
      "BE": "l-Belġju",
      "BG": "Il-Bulgarija",
      "BY": "Bjelorussja",
      "CH": "Svizzera",
      "CY": "Ċipru",
      "CZ": "iċ-Ċekja",
      "DE": "Il-Ġermanja",
      "DK": "Id-Danimarka",
      "EE": "L-Estonja",
      "EL": "Il-Greċja",
      "ES": "Spanja",
      "FI": "Il-Finlandja",
      "FR": "Franza",
      "GE": "Ġeorġja",
      "HR": "Il-Kroazja",
      "HU": "L-Ungerija",
      "IE": "L-Irlanda",
      "IS": "Islanda",
      "IT": "L-Italja",
      "KS": "Kosovo*",
      "LI": "Liechtenstein",
      "LT": "Il-Greċja",
      "LU": "Il-Lussemburgu",
      "LV": "Il-Latvja",
      "MC": "Monaco",
      "MD": "Moldova",
      "ME": "Il-Montenegro",
      "MK": "Dik li kienetir-Repubblika Jugoslavatal-Maċedonja",
      "MT": "Malta",
      "NL": "Il-Pajjiżi l-Baxxi",
      "NO": "Norveġja",
      "PL": "Il-Polonja",
      "PT": "Il-Portugall",
      "RO": "Ir-Rumanija",
      "RS": "Is-Serbja",
      "RU": "Russja",
      "SE": "L-Isvezja",
      "SI": "Is-Slovenja",
      "SK": "s-Slovakkja",
      "SM": "San Marino",
      "TR": "It-Turkija",
      "UA": "Ukraina",
      "UK": "Ir-Renju Unit",
      "VA": "Vatikan"
    },
    "nl": {
      "AD": "Andorra",
      "AL": "Albanië",
      "AM": "Armenië",
      "AT": "Oostenrijk",
      "AZ": "Azerbeidzjan",
      "BA": "Bosnië en Herzegovina",
      "BE": "België",
      "BG": "Bulgarije",
      "BY": "Wit-Rusland",
      "CH": "Zwitserland",
      "CY": "Cyprus",
      "CZ": "Tsjechië",
      "DE": "Duitsland",
      "DK": "Denemarken",
      "EE": "Estland",
      "EL": "Griekenland",
      "ES": "Spanje",
      "FI": "Finland",
      "FR": "Frankrijk",
      "GE": "Georgië",
      "HR": "Kroatië",
      "HU": "Hongarije",
      "IE": "Ierland",
      "IS": "IJsland",
      "IT": "Italië",
      "KS": "Kosovo*",
      "LI": "Liechtenstein",
      "LT": "Litouwen",
      "LU": "Luxemburg",
      "LV": "Letland",
      "MC": "Monaco",
      "MD": "Moldavië",
      "ME": "Montenegro",
      "MK": "Voormalige Joegoslavische Republiek Macedonië",
      "MT": "Malta",
      "NL": "Nederland",
      "NO": "Noorwegen",
      "PL": "Polen",
      "PT": "Portugal",
      "RO": "Roemenië",
      "RS": "Servië",
      "RU": "Rusland",
      "SE": "Zweden",
      "SI": "Slovenië",
      "SK": "Slowakije",
      "SM": "San Marino",
      "TR": "Turkije",
      "UA": "Oekraïne",
      "UK": "Verenigd Koninkrijk",
      "VA": "Vaticaanstad"
    },
    "pl": {
      "AD": "Andora",
      "AL": "Albania",
      "AM": "Armenia",
      "AT": "Austria",
      "AZ": "Azerbejdżan",
      "BA": "Bośnia i Hercegowina",
      "BE": "Belgia",
      "BG": "Bułgaria",
      "BY": "Białoruś",
      "CH": "Szwajcaria",
      "CY": "Cypr",
      "CZ": "Czechy",
      "DE": "Niemcy",
      "DK": "Dania",
      "EE": "Estonia",
      "EL": "Grecja",
      "ES": "Hiszpania",
      "FI": "Finlandia",
      "FR": "Francja",
      "GE": "Gruzja",
      "HR": "Chorwacja",
      "HU": "Węgry",
      "IE": "Irlandia",
      "IS": "Islandia",
      "IT": "Włochy",
      "KS": "Kosowo",
      "LI": "Liechtenstein",
      "LT": "Litwa",
      "LU": "Luksemburg",
      "LV": "Łotwa",
      "MC": "Monako",
      "MD": "Mołdawia",
      "ME": "Czarnogóra",
      "MK": "Była Jugosłowiańska Republika Macedonii",
      "MT": "Malta",
      "NL": "Holandia",
      "NO": "Norwegia",
      "PL": "Polska",
      "PT": "Portugalia",
      "RO": "Rumunia",
      "RS": "Serbia",
      "RU": "Rosja",
      "SE": "Szwecja",
      "SI": "Słowenia",
      "SK": "Słowacja",
      "SM": "San Marino",
      "TR": "Turcja",
      "UA": "Ukraina",
      "UK": "Zjednoczone Królestwo",
      "VA": "Watykan"
    },
    "pt": {
      "AD": "Andorra",
      "AL": "Albânia",
      "AM": "Arménia",
      "AT": "Áustria",
      "AZ": "Azerbaijão ",
      "BA": "Bósnia e Herzegovina",
      "BE": "Bélgica",
      "BG": "Bulgária",
      "BY": "Bielorrússia",
      "CH": "Suíça",
      "CY": "Chipre",
      "CZ": "Chéquia",
      "DE": "Alemanha",
      "DK": "Dinamarca",
      "EE": "Estónia",
      "EL": "Grécia",
      "ES": "Espanha",
      "FI": "Finlândia",
      "FR": "França",
      "GE": "Geórgia",
      "HR": "Croácia",
      "HU": "Hungria",
      "IE": "Irlanda",
      "IS": "Islândia",
      "KS": "Kosovo*",
      "IT": "Itália",
      "LI": "Liechtenstein",
      "LT": "Lituânia",
      "LU": "Luxemburgo",
      "LV": "Letónia",
      "MC": "Mónaco",
      "MD": "Moldávia",
      "ME": "Montenegro",
      "MK": "Antiga República jugoslava da Macedónia",
      "MT": "Malta",
      "NL": "Países Baixos",
      "NO": "Noruega",
      "PL": "Polónia",
      "PT": "Portugal",
      "RO": "Roménia",
      "RS": "Sérvia",
      "RU": "Rússia",
      "SE": "Suécia",
      "SI": "Eslovénia",
      "SK": "Eslováquia",
      "SM": "São Marino",
      "TR": "Turquia",
      "UA": "Ucrânia",
      "UK": "Reino Unido",
      "VA": "Vaticano"
    },
    "ro": {
      "AD": "Andorra",
      "AL": "Albania",
      "AM": "Armenia",
      "AT": "Austria",
      "AZ": "Azerbaidjan",
      "BA": "Bosnia şi Herţegovina",
      "BE": "Belgia",
      "BG": "Bulgaria",
      "BY": "Belarus",
      "CH": "Elveția",
      "CY": "Cipru",
      "CZ": "Cehia",
      "DE": "Germania",
      "DK": "Danemarca",
      "EE": "Estonia",
      "EL": "Grecia",
      "ES": "Spania",
      "FI": "Finlanda",
      "FR": "Franța",
      "GE": "Georgia",
      "HR": "Croația",
      "HU": "Ungaria",
      "IE": "Irlanda",
      "IS": "Islanda",
      "IT": "Italia",
      "KS": "Kosovo*",
      "LI": "Liechtenstein",
      "LT": "Lituania",
      "LU": "Luxemburg",
      "LV": "Letonia",
      "MC": "Monaco",
      "MD": "Moldova",
      "ME": "Montenegro",
      "MK": "Fosta Republică Iugoslavă a Macedoniei",
      "MT": "Malta",
      "NL": "Țările de Jos",
      "NO": "Norvegia",
      "PL": "Polonia",
      "PT": "Portugalia",
      "RO": "România",
      "RS": "Serbia",
      "RU": "Rusia",
      "SE": "Suedia",
      "SI": "Slovenia",
      "SK": "Slovacia",
      "SM": "San Marino",
      "TR": "Turcia",
      "UA": "Ucraina",
      "UK": "Regatul Unit",
      "VA": "Vatican"
    },
    "sk": {
      "AD": "Andorra",
      "AL": "Albánsko",
      "AM": "Arménsko",
      "AT": "Rakúsko",
      "AZ": "Azerbajdžan",
      "BA": "Bosna a Hercegovina",
      "BE": "Belgicko",
      "BG": "Bulharsko",
      "BY": "Bielorusko",
      "CH": "Švajčiarsko",
      "CY": "Cyprus",
      "CZ": "Česko",
      "DE": "Nemecko",
      "DK": "Dánsko",
      "EE": "Estónsko",
      "EL": "Grécko",
      "ES": "Španielsko",
      "FI": "Fínsko",
      "FR": "Francúzsko",
      "GE": "Gruzínsko",
      "HR": "Chorvátsko",
      "HU": "Maďarsko",
      "IE": "Írsko",
      "IS": "Island",
      "IT": "Taliansko",
      "KS": "Kosovo*",
      "LI": "Lichtenštajnsko",
      "LT": "Litva",
      "LU": "Luxembursko",
      "LV": "Lotyšsko",
      "MC": "Monako",
      "MD": "Moldavsko",
      "ME": "Čierna Hora",
      "MK": "Bývalá juhoslovanská republika Macedónsko",
      "MT": "Malta",
      "NL": "Holandsko",
      "NO": "Nórsko",
      "PL": "Poľsko",
      "PT": "Portugalsko",
      "RO": "Rumunsko",
      "RS": "Srbsko",
      "RU": "Rusko",
      "SE": "Švédsko",
      "SI": "Slovinsko",
      "SK": "Slovensko",
      "SM": "San Maríno",
      "TR": "Turecko",
      "UA": "Ukrajina",
      "UK": "Spojené kráľovstvo",
      "VA": "Vatikán"
    },
    "sl": {
      "AD": "Andora",
      "AL": "Albanija",
      "AM": "Armenija",
      "AT": "Avstrija",
      "AZ": "Azerbajdžan",
      "BA": "Bosna in Hercegovina",
      "BE": "Belgija",
      "BG": "Bolgarija",
      "BY": "Belorusija",
      "CH": "Švica",
      "CY": "Ciper",
      "CZ": "Češka",
      "DE": "Nemčija",
      "DK": "Danska",
      "EE": "Estonija",
      "EL": "Grčija",
      "ES": "Španija",
      "FI": "Finska",
      "FR": "Francija",
      "GE": "Gruzija",
      "HR": "Hrvaška",
      "HU": "Madžarska",
      "IE": "Irska",
      "IS": "Islandija",
      "IT": "Italija",
      "KS": "Kosovu",
      "LI": "Lihtenštajn",
      "LT": "Litva",
      "LU": "Luksemburg",
      "LV": "Latvija",
      "MC": "Monako",
      "MD": "Moldavija",
      "ME": "Črna gora",
      "MK": "Nekdanja jugoslovanska republika Makedonija",
      "MT": "Malta",
      "NL": "Nizozemska",
      "NO": "Norveška",
      "PL": "Poljska",
      "PT": "Portugalska",
      "RO": "Romunija",
      "RS": "Srbija",
      "RU": "Rusija",
      "SE": "Švedska",
      "SI": "Slovenija",
      "SK": "Slovaška",
      "SM": "San Marino",
      "TR": "Turčija",
      "UA": "Ukrajina",
      "UK": "Združeno kraljestvo",
      "VA": "Vatikan"
    },
    "fi": {
      "AD": "Andorra",
      "AL": "Albania",
      "AM": "Armenia",
      "AT": "Itävalta",
      "AZ": "Azerbaidžan",
      "BA": "Bosnia ja Hertsegovina",
      "BE": "Belgia",
      "BG": "Bulgaria",
      "BY": "Valko-Venäjä",
      "CH": "Sveitsi",
      "CY": "Kypros",
      "CZ": "Tšekki",
      "DE": "Saksa",
      "DK": "Tanska",
      "EE": "Viro",
      "EL": "Kreikka",
      "ES": "Espanja",
      "FI": "Suomi",
      "FR": "Ranska",
      "GE": "Georgia",
      "HR": "Kroatia",
      "HU": "Unkari",
      "IE": "Irlanti",
      "IS": "Islanti",
      "IT": "Italia",
      "KS": "Kosovo*",
      "LI": "Liechtenstein",
      "LT": "Liettua",
      "LU": "Luxemburg",
      "LV": "Latvia",
      "MC": "Monaco",
      "MD": "Moldova",
      "ME": "Montenegro",
      "MK": "Entinen Jugoslavian tasavalta Makedonia",
      "MT": "Malta",
      "NL": "Alankomaat",
      "NO": "Norja",
      "PL": "Puola",
      "PT": "Portugali",
      "RO": "Romania",
      "RS": "Serbia",
      "RU": "Venäjä",
      "SE": "Ruotsi",
      "SI": "Slovenia",
      "SK": "Slovakia",
      "SM": "San Marino",
      "TR": "Turkki",
      "UA": "Ukraina",
      "UK": "Yhdistynyt kuningaskunta",
      "VA": "Vatikaani"
    },
    "sv": {
      "AD": "Andorra",
      "AL": "Albanien",
      "AM": "Armenien",
      "AT": "Österrike",
      "AZ": "Azerbajdzjan",
      "BA": "Bosnien och Hercegovina",
      "BE": "Belgien",
      "BG": "Bulgarien",
      "BY": "Vitryssland",
      "CH": "Schweiz",
      "CY": "Cypern",
      "CZ": "Tjeckien",
      "DE": "Tyskland",
      "DK": "Danmark",
      "EE": "Estland",
      "EL": "Grekland",
      "ES": "Spanien",
      "FI": "Finland",
      "FR": "Frankrike",
      "GE": "Georgien",
      "HR": "Kroatien",
      "HU": "Ungern",
      "IE": "Irland",
      "IS": "Island",
      "IT": "Italien",
      "KS": "Kosovo*",
      "LI": "Liechtenstein",
      "LT": "Litauen",
      "LU": "Luxemburg",
      "LV": "Lettland",
      "MC": "Monaco",
      "MD": "Moldavien",
      "ME": "Montenegro",
      "MK": "Före detta jugoslaviska republiken Makedonien",
      "MT": "Malta",
      "NL": "Nederländerna",
      "NO": "Norge",
      "PL": "Polen",
      "PT": "Portugal",
      "RO": "Rumänien",
      "RS": "Serbien",
      "RU": "Ryssland",
      "SE": "Sverige",
      "SI": "Slovenien",
      "SK": "Slovakien",
      "SM": "San Marino",
      "TR": "Turkiet",
      "UA": "Ukraina",
      "UK": "Storbritannien",
      "VA": "Vatikanstaten"
    }
  },

  centroid: {
    "AD":{"l":"Andorra","c":[42.546212,1.600286]},
    "AE":{"l":"United Arab Emirates","c":[24.53,52.49]},
    "AF":{"l":"Afghanistan","c":[34.52,66.01]},
    "AG":{"l":"Antigua and Barbuda","c":[17.080501,-61.789423]},
    "AI":{"l":"Anguilla","c":[18.210013,-63.072130]},
    "AL":{"l":"Albania","p":"left","c":[41.071015,20.169747]},
    "AM":{"l":"Armenia","c":[40.76,44.08]},
    "AN":{"l":"Netherlands Antilles","c":[12.142252,-68.945576]},
    "AO":{"l":"Angola","p":"left","c":[-12.734911,17.907223]},
    "AQ":{"l":"Antarctica","c":[-80.724251,0.000000]},
    "AR":{"l":"Argentina","c":[-37.37,-68.29]},
    "AS":{"l":"American Samoa","c":[-14.293331,-170.702385]},
    "AT":{"l":"Austria","c":[47.451856,13.345388]},
    "AU":{"l":"Australia","c":[-26.4390743,133.281323]},
    "AW":{"l":"Aruba","c":[12.499303,-69.964001]},
    "AZ":{"l":"Azerbaijan","c":[40.399857,47.698690]},
    "BA":{"l":"Bosnia and Herzegovina","c":[44.641641,16.476182]},
    "BB":{"l":"Barbados","c":[13.136483,-59.534649]},
    "BD":{"l":"Bangladesh","c":[23.911855,90.350998]},
    "BE":{"l":"Belgium","p":"center","c":[50.712408,4.476941]},
    "BF":{"l":"Burkina Faso","p":"center","c":[12.800035,-1.556761]},
    "BG":{"l":"Bulgaria","p":"center","c":[42.464545,25.482322]},
    "BH":{"l":"Bahrain","c":[26.042631,50.548613]},
    "BI":{"l":"Burundi","c":[-3.512922,29.920395]},
    "BJ":{"l":"Benin","p":"center","c":[10.6,1.54]},
    "BM":{"l":"Bermuda","p":"center","c":[32.279828,-64.785473]},
    "BN":{"l":"Brunei Darussalam","c":[4.009026,114.614049]},
    "BO":{"l":"Bolivia","p":"center","c":[-17.276044,-63.549429]},
    "BR":{"l":"Brazil","p":"center","c":[-8.58,-51.24]},
    "BT":{"l":"Bhutan","c":[27.474721,90.442238]},
    "BV":{"l":"Bouvet Island","c":[-54.431739,3.411738]},
    "BW":{"l":"Botswana","c":[-21.885243,24.680158]},
    "BY":{"l":"Belarus","c":[53.28,25.75]},
    "BZ":{"l":"Belize","p":"center","c":[17.210905,-88.652836]},
    "CA":{"l":"Canada","c":[61.02,-107.75]},
    "CC":{"l":"Cocos (Keeling) Islands","c":[-12.178974,96.844231]},
    "CD":{"l":"Democratic Republic of the Congo","p":"center","c":[-2.86,23.51]},
    "CF":{"l":"Central African Republic","c":[6.997428,20.941759]},
    "CG":{"l":"Congo (Brazzaville)","c":[-1.334604,14.927424]},
    "CH":{"l":"Switzerland","p":"center","c":[46.825969,8.224051]},
    "CI":{"l":"C&ocirc;te<br>d'Ivoire","p":"center","c":[7.766235,-5.547100]},
    "CL":{"l":"Chile","p":"left","c":[-31.88,-71.19]},
    "CM":{"l":"Cameroon","p":"left","c":[3.91,12.74]},
    "CN":{"l":"China","c":[32.320240,104.169482]},
    "CO":{"l":"Colombia","p":"left","c":[3.365166,-72.958530]},
    "CR":{"l":"Costa Rica","c":[9.479045,-84.253307]},
    "CU":{"l":"Cuba","p":"center","c":[22.100304,-79.544601]},
    "CX":{"l":"Christmas Island","c":[-10.492947,105.629269]},
    "CY":{"l":"Cyprus","p":"center","c":[35.048258,33.428682]},
    "CZ":{"l":"Czechia","p":"center","c":[49.871095,15.474998]},
    "DE":{"l":"Germany","p":"center","c":[51.451572,9.854074]},
    "DJ":{"l":"Djibouti","c":[11.265559,42.595211]},
    "DK":{"l":"Denmark","p":"center","c":[55.847388,9.516828]},
    "DM":{"l":"Dominica","c":[15.394660,-61.364130]},
    "DO":{"l":"Dominican Republic","c":[18.929523,-70.161743]},
    "DZ":{"l":"Algeria","c":[28.555743,1.652841]},
    "EC":{"l":"Ecuador","p":"left","c":[-1.179933,-78.095795]},
    "EE":{"l":"Estonia","p":"center","c":[58.723725,25.806997]},
    "EG":{"l":"Egypt","p":"center","c":[26.648129,30.246479]},
    "EH":{"l":"Western Sahara","p":"left","c":[25.381102,-12.886729]},
    "ER":{"l":"Eritrea","c":[15.54,37.35]},
    "ES":{"l":"Spain","p":"center","c":[40.068952,-2.988296]},
    "ET":{"l":"Ethiopia","c":[9.226587,40.493059]},
    "FI":{"l":"Finland","p":"center","c":[62.336196,25.167564]},
    "FJ":{"l":"Fiji","c":[-17.830981,177.973381]},
    "FK":{"l":"Falkland Islands (Malvinas)","c":[-52.014991,-58.721048]},
    "FM":{"l":"Federated States of Micronesia","c":[6.872111,158.223137]},
    "FR":{"l":"France","p":"center","c":[47.273641,2.218567]},
    "GA":{"l":"Gabon","p":"left","c":[-1.71,10.11]},
    "GD":{"l":"Grenada","c":[12.006696,-61.698942]},
    "GE":{"l":"Georgia","p":"left","c":[42.047071,43.365799]},
    "GG":{"l":"Guernsey","c":[49.454897,-2.595800]},
    "GH":{"l":"Ghana","p":"center","c":[8.93,-1.23]},
    "GI":{"l":"Gibraltar","c":[36.135809,-5.352833]},
    "GL":{"l":"Greenland","c":[77.5,-42.71]},
    "GM":{"l":"Gambia","p":"left","c":[13.566612,-15.311434]},
    "GN":{"l":"Guinea","c":[11.002634,-11.283845]},
    "GQ":{"l":"Equatorial Guinea","p":"left","c":[1.585783,10.341294]},
    "EL":{"l":"Greece","p":"center","c":[39.264526,22.121999]},
    "GS":{"l":"South Georgia and the South Sandwich Islands","c":[-54.207367,-36.906628]},
    "GT":{"l":"Guatemala","p":"center","c":[15.798070,-90.232346]},
    "GU":{"l":"Guam","c":[13.456334,144.786613]},
    "GW":{"l":"Guinea-Bissau","p":"left","c":[11.357795,-15.172582]},
    "GY":{"l":"Guyana","c":[7.32,-59.41]},
    "HK":{"l":"Hong Kong","c":[22.442483,114.152221]},
    "HM":{"l":"Heard Island and McDonald Islands","c":[-53.103401,73.556225]},
    "HN":{"l":"Honduras","c":[15.71,-86.253098]},
    "HR":{"l":"Croatia","p":"left","c":[45.114794,15.568608]},
    "HT":{"l":"Haiti","c":[18.321572,-73.047256]},
    "HU":{"l":"Hungary","p":"center","c":[47.124932,19.505190]},
    "IE":{"l":"Ireland","c":[53.608627,-9.039122]},
    "IL":{"l":"Israel","c":[30.451821,34.968707]},
    "IM":{"l":"Isle of Man","c":[54.229110,-4.555113]},
    "IN":{"l":"India","p":"center","c":[22.27,78.84]},
    "IO":{"l":"British Indian Ocean Territory","c":[-7.431772,72.422489]},
    "IQ":{"l":"Iraq","c":[33.592960,43.684204]},
    "IR":{"l":"Iran","c":[31.781067,53.674751]},
    "IS":{"l":"Iceland","p":"center","c":[64.790777,-18.813530]},
    "IT":{"l":"Italy","p":"center","c":[42.793509,12.573787]},
    "JE":{"l":"Jersey","c":[49.229244,-2.141057]},
    "JM":{"l":"Jamaica","p":"center","c":[18.118645,-77.273479]},
    "JO":{"l":"Jordan","p":"center","c":[30.652236,37.130589]},
    "JP":{"l":"Japan","c":[35.350846,136.469032]},
    "KE":{"l":"Kenya","p":"center","c":[0.014633,37.903969]},
    "KG":{"l":"Kyrgyzstan","p":"center","c":[41.670312,74.779899]},
    "KH":{"l":"Cambodia","c":[12.517175,104.983860]},
    "KI":{"l":"Kiribati","c":[1.893153,-157.663055]},
    "KM":{"l":"Comoros","c":[-11.612900,43.359976]},
    "KN":{"l":"Saint Kitts and Nevis","c":[17.335632,-62.746368]},
    "KP":{"l":"Democratic People's Republic of Korea","c":[40.35,125.6]},
    "KR":{"l":"Republic of Korea","c":[36.624914,127.850220]},
    "KW":{"l":"Kuwait","c":[29.531469,47.494528]},
    "KY":{"l":"Cayman Islands","p":"center","c":[19.315161,-81.262047]},
    "KZ":{"l":"Kazakhstan","c":[48.005457,66.902257]},
    "LA":{"l":"Lao PDR","c":[18.803711,103.895042]},
    "LB":{"l":"Lebanon","p":"left","c":[33.942798,35.869817]},
    "LC":{"l":"Saint Lucia","c":[13.882687,-60.974176]},
    "LI":{"l":"Liechtenstein","c":[47.137731,9.554136]},
    "LK":{"l":"Sri Lanka","c":[7.663577,80.785755]},
    "LR":{"l":"Liberia","p":"center","c":[6.345426,-9.428598]},
    "LS":{"l":"Lesotho","c":[-29.69,27.73]},
    "LT":{"l":"Lithuania","p":"center","c":[55.543911,23.942214]},
    "LU":{"l":"Luxembourg","c":[49.752865,6.133351]},
    "LV":{"l":"Latvia","p":"center","c":[57.144537,24.606126]},
    "LY":{"l":"Libya","c":[26.979474,17.268820]},
    "MA":{"l":"Morocco","p":"left","c":[31.749754,-7.080164]},
    "MC":{"l":"Monaco","c":[43.731056,7.424479]},
    "MD":{"l":"Moldova","c":[46.848699,28.392618]},
    "ME":{"l":"Montenegro","p":"left","c":[42.398732,19.393241]},
    "MG":{"l":"Madagascar","p":"center","c":[-20.173248,46.854328]},
    "MK":{"l":"Republic of North Macedonia","c":[41.595501,21.743243]},
    "ML":{"l":"Mali","c":[18.954937,-3.998821]},
    "MM":{"l":"Myanmar","p":"left","c":[16.930476,96.678747]},
    "MN":{"l":"Mongolia","c":[46.005858,103.835776]},
    "MR":{"l":"Mauritania","p":"left","c":[20.584700,-10.947097]},
    "MS":{"l":"Montserrat","c":[16.744752,-62.194502]},
    "MT":{"l":"Malta","c":[35.883816,14.447624]},
    "MU":{"l":"Mauritius","c":[-20.261343,57.551741]},
    "MV":{"l":"Maldives","p":"center","c":[4.13,73.56]},
    "MW":{"l":"Malawi","c":[-13.33,33.16]},
    "MX":{"l":"Mexico","p":"center","c":[23.866098,-101.930061]},
    "MY":{"l":"Malaysia","p":"center","c":[2.33,112.76]},
    "MZ":{"l":"Mozambique","c":[-22.55,32.3]},
    "NA":{"l":"Namibia","p":"left","c":[-23.190118,18.486166]},
    "NC":{"l":"New Caledonia","c":[-21.417425,165.506737]},
    "NE":{"l":"Niger","c":[17.262904,8.080946]},
    "NF":{"l":"Norfolk Island","c":[-29.025284,168.049789]},
    "NG":{"l":"Nigeria","p":"center","c":[8.948073,8.674252]},
    "NI":{"l":"Nicaragua","c":[12.621321,-85.424057]},
    "NL":{"l":"The Netherlands","p":"left","c":[52.068429,6.330293]},
    "NO":{"l":"Norway","p":"left","c":[60.607487,8.804793]},
    "NP":{"l":"Nepal","p":"center","c":[28.377289,84.127804]},
    "NR":{"l":"Nauru","c":[-0.529585,166.922142]},
    "NU":{"l":"Niue","c":[-19.050124,-169.863091]},
    "NZ":{"l":"New Zealand","c":[-44.505545,170.366623]},
    "OM":{"l":"Oman","c":[19.35,55.72]},
    "PA":{"l":"Panama","p":"center","c":[8.49,-80.38]},
    "PE":{"l":"Peru","p":"left","c":[-7.795546,-75.002365]},
    "PG":{"l":"Papua New Guinea","c":[-6.756244,145.859314]},
    "PK":{"l":"Pakistan","c":[28.73,66.01]},
    "PL":{"l":"Poland","p":"center","c":[52.378408,19.134334]},
    "PM":{"l":"Saint Pierre and Miquelon","c":[46.858127,-56.336824]},
    "PN":{"l":"Pitcairn","c":[-24.362156,-128.316376]},
    "PR":{"l":"Puerto Rico","p":"center","c":[18.228412,-66.428890]},
    "PS":{"l":"Palestinian Territory, Occupied","c":[31.565038,35.228220]},
    "PT":{"l":"Portugal","p":"left","c":[39.423966,-7.844941]},
    "PW":{"l":"Palau","c":[7.480643,134.563889]},
    "PY":{"l":"Paraguay","c":[-22.94,-61.13]},
    "QA":{"l":"Qatar","c":[25.346129,51.196939]},
    "RO":{"l":"Romania","p":"center","c":[45.728117,24.988627]},
    "RS":{"l":"Serbia","p":"center","c":[43.766217,20.926449]},
    "KS":{"l":"Kosovo*","p":"center","c":[42.569264,20.808105]},
    "XK":{"l":"Kosovo*","p":"center","c":[42.569264,20.808105]},
    "RW":{"l":"Rwanda","c":[-2.061275,29.876376]},
    "SA":{"l":"Saudi Arabia","p":"center","c":[23.302881,45.120351]},
    "SD":{"l":"Sudan","p":"center","c":[12.974570,30.209492]},
    "SE":{"l":"Sweden","p":"center","c":[59.062697,14.634344]},
    "SG":{"l":"Singapore","c":[1.365788,103.822876]},
    "SI":{"l":"Slovenia","p":"center","c":[46.050954,14.586138]},
    "SJ":{"l":"Svalbard and Jan Mayen Islands","c":[76.859136,16.096959]},
    "SK":{"l":"Slovakia","p":"center","c":[48.801532,19.700049]},
    "SL":{"l":"Sierra Leone","p":"left","c":[8.560284,-11.795934]},
    "SM":{"l":"San Marino","c":[43.933599,12.459727]},
    "SN":{"l":"Senegal","p":"left","c":[15.52,-14.19]},
    "SO":{"l":"Somalia","c":[4.400311,46.200832]},
    "SR":{"l":"Suriname","p":"center","c":[4.04,-55.99]},
    "SS":{"l":"South Sudan","p":"center","c":[7.2099,30.0585]},
    "ST":{"l":"Sao Tome and Principe","p":"left","c":[0.247583,6.619353]},
    "SV":{"l":"El Salvador","p":"center","c":[13.749611,-88.918789]},
    "SY":{"l":"Syrian Arab Republic","c":[35.96,36.96]},
    "SZ":{"l":"Eswatini","c":[-26.523595,31.465684]},
    "TD":{"l":"Chad","p":"center","c":[15.200293,18.738068]},
    "TF":{"l":"French Southern Territories","c":[-49.606858,69.648491]},
    "TG":{"l":"Togo","p":"center","c":[8.73,1.05]},
    "TH":{"l":"Thailand","c":[15.71,99.54]},
    "TJ":{"l":"Tajikistan","c":[38.82,70]},
    "TK":{"l":"Tokelau","c":[-9.192961,-171.853912]},
    "TL":{"l":"Timor-Leste","c":[-8.757930,126.116924]},
    "TM":{"l":"Turkmenistan","p":"left","c":[39.23,59.63]},
    "TN":{"l":"Tunisia","c":[33.796607,9.561549]},
    "TR":{"l":"Turkey","p":"center","c":[39.128664,35.439795]},
    "TT":{"l":"Trinidad and Tobago","c":[10.420798,-61.417133]},
    "TV":{"l":"Tuvalu","c":[-7.478603,178.678452]},
    "TZ":{"l":"United Republic of Tanzania","c":[-6.413502,34.885195]},
    "UA":{"l":"Ukraine","p":"center","c":[49.350797,31.182740]},
    "UG":{"l":"Uganda","p":"center","c":[1.347100,32.304650]},
    "UK":{"l":"United Kingdom","p":"center","c":[52.773808,-1.732612]},
    "UM":{"l":"United States Minor Outlying Islands","c":[6.478542,-162.561394]},
    "US":{"l":"United States of America","p":"center","c":[39.77,-100.46]},
    "UY":{"l":"Uruguay","p":"center","c":[-32.895153,-55.758327]},
    "UZ":{"l":"Uzbekistan","p":"center","c":[41.214111,64.565969]},
    "VC":{"l":"Saint Vincent and Grenadines","p":"left","c":[13.243565,-61.196320]},
    "VE":{"l":"Venezuela","c":[8.02,-70.31]},
    "VI":{"l":"Virgin Islands, US","c":[17.740486,-64.736294]},
    "VN":{"l":"Viet Nam","c":[10.106801,105.804436]},
    "WS":{"l":"Samoa","c":[-13.627023,-172.482437]},
    "XC":{"l":"Aksai Chin (Disputed Territory)","c":[34.970190,79.133766]},
    "XD":{"l":"Arunachal Pradesh","c":[28.416225,94.485949]},
    "XF":{"l":"Hala'Ib Triangle (Disputed Territory)","c":[22.514518,35.488611]},
    "XG":{"l":"Ilemi Triangle (Disputed Territory)","c":[4.752479,34.943615]},
    "XH":{"l":"Jammu Kashmir (Disputed Territory)","c":[32.699213,75.910062]},
    "XI":{"l":"Kuril Islands (Disputed Territory)","c":[45.096674,147.877754]},
    "XJ":{"l":"Liancourt Rock (Disputed Territory)","c":[37.242999,131.870354]},
    "XL":{"l":"Navassa Island (Disputed Territory)","c":[18.408649,-75.014114]},
    "XO":{"l":"Fr Territory (Juan de Nova, Glorioso, Europa, Tromelin, Bassas Da India)","c":[-22.358672,40.356247]},
    "YE":{"l":"Yemen","c":[15.856168,47.851362]},
    "YT":{"l":"Mayotte","c":[-12.965217,45.136776]},
    "ZA":{"l":"South Africa","c":[-32.77,18.98]},
    "ZM":{"l":"Zambia","p":"center","c":[-14.596892,27.852537]},
    "ZW":{"l":"Zimbabwe","c":[-19.39,26.76]},
    "RU":{"l":"Russia","c":[63.882461,103.658728]},
    "BS":{"l":"Bahamas","p":"center","c":[24.254338,-76.611199]},
    "CK":{"l":"Cook Islands","c":[-19.211441,-158.978210]},
    "CV":{"l":"Cabo Verde","p":"left","c":[15.941233,-23.980244]},
    "FO":{"l":"Faroe Islands","c":[62.068101,-6.892328]},
    "ID":{"l":"Indonesia","c":[-2.226076,117.277418]},
    "MH":{"l":"Marshall Islands","c":[7.833452,169.598453]},
    "MO":{"l":"澳門-Macau","c":[22.162656,113.557201]},
    "MP":{"l":"Northern Mariana Islands-Notte Mariånas-Northern Mariana Islands","c":[15.774550,145.604227]},
    "PF":{"l":"French Polynesia","c":[-15.422801,-145.248614]},
    "PH":{"l":"Philippines","c":[11.734691,122.867106]},
    "SB":{"l":"Solomon Islands","c":[-8.899535,159.600800]},
    "SC":{"l":"Seychelles","c":[-6.693755,51.835766]},
    "SH":{"l":"Saint Helena, Ascension and Tristan Da Cunha","c":[-25.452897,-10.427469]},
    "TC":{"l":"Turks and Caicos Islands","c":[21.750061,-71.856153]},
    "TO":{"l":"Tonna","c":[-19.858992,-174.847166]},
    "VA":{"l":"Vatican","c":[41.903074,12.456119]},
    "VG":{"l":"Virgin Islands, British","c":[18.511488,-64.515780]},
    "VU":{"l":"Vanuatu","c":[-16.195911,167.703057]},
    "WF":{"l":"Territory of the Wallis and Futuna Islands","c":[-13.829207,-177.194355]},
    "XA":{"l":"Paracel Islands (Disputed Territory)","c":[16.368120,111.875769]},
    "XB":{"l":"Spratly Islands (Disputed Territory)","c":[10.611653,115.130209]},
    "XE":{"l":"China/India (Disputed Territory)","c":[32.651673,79.372438]},
    "XM":{"l":"Scarborough Reef (Disputed Territory)","c":[15.111462,117.764204]},
    "XN":{"l":"Senkaku Islands (Disputed Territory)","c":[25.770933,123.541477]}
  },

  bounds: {

    "ES1": [36.007, -9.298, 43.789, 3.322],
    "ES2": [27.641, -18.171, 29.349, -13.37],
    "ES3": [35.274, -2.97, 35.318, -2.927],
    "ES4": [35.873, -5.382, 35.913, -5.343],
    "ES5": [39.262, 2.337, 40.091, 4.312],

    "FR1": [42.333, -4.792, 51.089, 8.233],
    "FR2": [2.12, -54.59, 5.745, -51.63],
    "FR3": [41.368, 8.554, 43, 9.559],
    "FR4": [-21.387, 55.217, -20.882, 55.837],
    "FR5": [-13, 45.043, -12.669, 45.237],
    "FR6": [14.381, -63.105, 18.146, -60.793],

    "PT1": [36.962, -9.501, 42.154, -6.189],
    "PT2": [36.915, -31.278, 39.538, -25.005],
    "PT3": [32.625, -17.268, 33.112, -16.287]

  }

};
